services:
  django-web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    container_name: skillpeak
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - celery-beat
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A server worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A server beat -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis